kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-storage-volume
  labels:
     name: prometheus-storage-volume
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi