kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-storage
  labels:
     name: grafana-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
